### ISSUE TITLE
Device requirements

### ISSUE THREAD

**Issue by somomomo** [mogenson/fitbit-heart-rate-service#1]
https://github.com/mogenson/fitbit-heart-rate-service/blob/4b98a5b7c893b164f6854f4fa349b3ef19ec5f02/README.md?plain=1#L13

Is there anything special about the Sense or Versa 3 that allows this? Could this method be used on other Fitbit models (like Versa 2 or Charge series, etc)?

**Comment by mogenson** [comment]
This setup should work on any Fitbit device that https://studio.fitbit.com supports. This project is currently configured to target Fitbit OS 5.0 (which only run on Sense and Versa 3 watches). I don't own any other Fitbit products, so I can't test them to be sure. Feel free to build the watch app for another device and try it out. You'll probably also need to adjust the graphics and layout for a different size display.

**Comment by somomomo** [comment]
Thanks for the quick response. I took a look at Fitbit Studio and now it's clear why this is the case. Fitbit SDK 5/6 supports Sense and Versa 3 while SDK 4.3 supports older models (Versa/Lite/2 and Ionic). It looks like the Charge series is SOL. I'll try to take a look at this for Versa 2 later.
