### ISSUE TITLE
Would like to upload to Google Play

### ISSUE THREAD

**Issue by randalln** [mogenson/fitbit-heart-rate-service#3]
Hi there.  I inherited a Fitbit Sense and was so glad to find your app in the Fitbit Gallery.

I [forked](https://github.com/randalln/fitbit-heart-rate-service) your repo and [updated](https://github.com/mogenson/fitbit-heart-rate-service/compare/main...randalln:fitbit-heart-rate-service:main) the Android app to play nice(r) with Android 14 (API 34).  My hope is to make further updates in the future.

In order to make it easier for people to find and use, I'd like to publish the Android app on Google Play.  I'd be happy to collaborate and push changes upstream to your repo, or I can just work from my fork.  Please let me know your preference and thanks again.

**Comment by mogenson** [comment]
Glad you could use this app and thanks for the work! I don't have a Fitbit Sense anymore, so this project hasn't seen any updates.

Feel free to publish the Android app on the Google Play Store and the Fitbit app on the Fitbit Gallery, if you'd like! Note: the Fitbit Gallery and Fitbit Studio are both slowly being shutdown: https://9to5google.com/2024/03/22/google-fitbit-apps-faces-eu-removal/

Next, I can either make you a maintainer of this repo so you can push and change whatever. Or, you can work out of your fork or start a new project. Please just add some link or acknowledgement to this repo.

Let me know what works!

**Comment by randalln** [comment]
> Feel free to publish the Android app on the Google Play Store and the Fitbit app on the Fitbit Gallery, if you'd like! Note: the Fitbit Gallery and Fitbit Studio are both slowly being shutdown: https://9to5google.com/2024/03/22/google-fitbit-apps-faces-eu-removal/

I saw that headline after I'd started my fork, so we might end up in the reverse situation (probably in the U.S. too eventually) where users are forced to sideload the watch app.  I've never done any Fitbit development, but I'll have to see if the [CLI SDK](https://dev.fitbit.com/build/guides/command-line-interface/) installation can be made relatively easy🤞 

> Next, I can either make you a maintainer of this repo so you can push and change whatever. Or, you can work out of your fork or start a new project. Please just add some link or acknowledgement to this repo.

If you don't mind, it might be helpful to be a maintainer of your repo so that I can update the README (adding a link the to Play Store at least for now).

Thank you for accommodating me!

**Comment by mogenson** [comment]
Sounds good. I sent you an invite to be a collaborator for this repo.

**Comment by mogenson** [comment]
@randalln I believe you should have commit access now. Let me know.
